-- MySQL Script generated by MySQL Workbench
-- Sat Jan 16 20:18:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_notitas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_notitas` ;

-- -----------------------------------------------------
-- Schema db_notitas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_notitas` DEFAULT CHARACTER SET utf8mb4 ;
USE `db_notitas` ;

-- -----------------------------------------------------
-- Table `db_notitas`.`notes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_notitas`.`notes` ;

CREATE TABLE IF NOT EXISTS `db_notitas`.`notes` (
  `id` INT(10) UNSIGNED NOT NULL,
  `title` VARCHAR(20) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `status` TINYINT(2) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
